"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Clock, DollarSign, Percent, RefreshCw, TrendingUp } from "lucide-react";
import { AdminError, AdminLoading } from "@/components/admin/AdminPageState";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { createClient } from "@/lib/supabase/client";

type RequestRow = { id: string; pricing_mode: string; status: string; total_amount: number | null; created_at: string; service_type: string; quote_only: boolean };
const BOOKED = new Set(["scheduled", "in_progress", "completed", "pending_review", "vendor_completed", "homeowner_confirmed", "review_requested", "reviewed", "closed"]);
const MODES = ["fixed", "deposit_quote", "custom_quote"];
export default function AdminPricingAnalyticsPage() {
  const [rows, setRows] = useState<RequestRow[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); const result = await createClient().from("service_requests").select("id, pricing_mode, status, total_amount, created_at, service_type, quote_only").order("created_at", { ascending: false }).limit(1000); if (result.error) setError(result.error.message); else setRows((result.data ?? []) as RequestRow[]); setLoading(false); }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const stats = useMemo(() => MODES.map((pricingMode) => { const subset = rows.filter((row) => row.pricing_mode === pricingMode); const booked = subset.filter((row) => BOOKED.has(row.status)); const revenue = booked.reduce((sum, row) => sum + Number(row.total_amount ?? 0), 0); return { pricingMode, total: subset.length, booked: booked.length, conversion: subset.length ? booked.length / subset.length * 100 : 0, revenue, average: booked.length ? revenue / booked.length : 0 }; }), [rows]);
  if (loading) return <AdminLoading label="Loading pricing analytics..." />; if (error) return <AdminError title="Pricing analytics could not be loaded" message={error} retry={() => void load()} />;
  const bookedRows = rows.filter((row) => BOOKED.has(row.status)); const totalRevenue = bookedRows.reduce((sum, row) => sum + Number(row.total_amount ?? 0), 0); const fixedShare = rows.length ? rows.filter((row) => row.pricing_mode === "fixed").length / rows.length * 100 : 0;
  return <div className="mx-auto w-full max-w-7xl space-y-6 p-4 sm:p-6 md:p-8"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-accent">Marketplace performance</p><h1 className="font-heading text-3xl font-semibold tracking-tight">Pricing Analytics</h1><p className="mt-2 text-sm text-muted-foreground">Compare live fixed-price and quote-based request conversion.</p></div><Button variant="outline" onClick={() => void load()}><RefreshCw />Refresh</Button></header><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[{ label: "Total Requests", value: rows.length, icon: TrendingUp }, { label: "Booked Revenue", value: money(totalRevenue), icon: DollarSign }, { label: "Fixed-Mode Share", value: `${fixedShare.toFixed(0)}%`, icon: Percent }, { label: "Sample Window", value: "Latest 1,000", icon: Clock }].map((stat) => <Card key={stat.label}><CardContent className="py-4"><div className="mb-1 flex items-center gap-2 text-sm text-muted-foreground"><stat.icon className="h-4 w-4" />{stat.label}</div><p className="text-2xl font-semibold">{stat.value}</p></CardContent></Card>)}</div><Card><CardHeader><CardTitle>Conversion by Pricing Mode</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[750px] text-sm"><thead className="border-y bg-muted/60"><tr><th className="p-4 text-left font-medium text-muted-foreground">Mode</th>{["Requests", "Booked", "Conversion", "Revenue", "Average Ticket"].map((heading) => <th key={heading} className="p-4 text-right font-medium text-muted-foreground">{heading}</th>)}</tr></thead><tbody className="divide-y">{stats.map((stat) => <tr key={stat.pricingMode}><td className="p-4"><Badge variant="outline">{label(stat.pricingMode)}</Badge></td><td className="p-4 text-right">{stat.total}</td><td className="p-4 text-right">{stat.booked}</td><td className="p-4 text-right font-medium">{stat.conversion.toFixed(1)}%</td><td className="p-4 text-right">{money(stat.revenue)}</td><td className="p-4 text-right">{money(stat.average)}</td></tr>)}</tbody></table></div><p className="p-4 text-xs text-muted-foreground">Booked includes scheduled and all subsequent fulfillment/review states. Revenue reflects stored request totals, not recognized accounting revenue.</p></CardContent></Card></div>;
}
function label(value: string) { return ({ fixed: "Fixed", deposit_quote: "Deposit + Quote", custom_quote: "Custom Quote" } as Record<string, string>)[value] ?? value; }
function money(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value); }
