"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { MessageSquare, RefreshCw, Search } from "lucide-react";
import { AdminEmpty, AdminError, AdminLoading } from "@/components/admin/AdminPageState";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { createClient } from "@/lib/supabase/client";
import { cn } from "@/lib/utils";

type Message = { id: string; service_request_id: string; sender_id: string; sender_role: string; content: string; created_at: string };
type RequestSummary = { id: string; service_type: string; status: string };
export default function AdminMessagesPage() {
  const [messages, setMessages] = useState<Message[]>([]); const [requests, setRequests] = useState<Record<string, RequestSummary>>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [search, setSearch] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const supabase = createClient(); const messageResult = await supabase.from("messages").select("id, service_request_id, sender_id, sender_role, content, created_at").order("created_at", { ascending: false }).limit(500); if (messageResult.error) throw messageResult.error; const nextMessages = (messageResult.data ?? []) as Message[]; const ids = [...new Set(nextMessages.map((message) => message.service_request_id))]; const requestResult = ids.length ? await supabase.from("service_requests").select("id, service_type, status").in("id", ids) : { data: [], error: null }; if (requestResult.error) throw requestResult.error; setMessages(nextMessages); setRequests(Object.fromEntries(((requestResult.data ?? []) as RequestSummary[]).map((request) => [request.id, request]))); } catch (reason) { console.error("Unable to load message audit", reason); setError(reason instanceof Error ? reason.message : "Messages could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const threads = useMemo(() => { const grouped: Record<string, Message[]> = {}; for (const message of messages) { grouped[message.service_request_id] ??= []; grouped[message.service_request_id].push(message); } return Object.entries(grouped).map(([id, thread]) => ({ id, messages: thread.sort((a, b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime()), latest: thread.reduce((latest, item) => new Date(item.created_at) > new Date(latest.created_at) ? item : latest) })).sort((a, b) => new Date(b.latest.created_at).getTime() - new Date(a.latest.created_at).getTime()); }, [messages]);
  const filtered = useMemo(() => { const query = search.trim().toLowerCase(); return threads.filter((thread) => !query || [thread.id, requests[thread.id]?.service_type ?? "", ...thread.messages.map((message) => message.content)].some((value) => value.toLowerCase().includes(query))); }, [requests, search, threads]);
  if (loading) return <AdminLoading label="Loading message audit..." />; if (error) return <AdminError title="Message audit could not be loaded" message={error} retry={() => void load()} />;
  return <div className="mx-auto w-full max-w-7xl space-y-6 p-4 sm:p-6 md:p-8"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-accent">Communications oversight</p><h1 className="font-heading text-3xl font-semibold tracking-tight">Message Audit</h1><p className="mt-2 text-sm text-muted-foreground">{messages.length} messages across {threads.length} service-request threads · read only</p></div><Button variant="outline" onClick={() => void load()}><RefreshCw />Refresh</Button></header><div className="relative max-w-xl"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search request, service, or message content..." className="pl-9" /></div>{filtered.length === 0 ? <Card><CardContent className="p-0"><AdminEmpty icon={MessageSquare} title={threads.length ? "No conversations match this search" : "No messages found"} /></CardContent></Card> : <div className="space-y-4">{filtered.map((thread) => <Card key={thread.id}><CardContent className="p-4"><div className="mb-4 flex flex-wrap items-center gap-2"><MessageSquare className="h-4 w-4 text-accent" /><span className="font-medium">{requests[thread.id]?.service_type ?? "Service Request"}</span>{requests[thread.id] && <Badge variant="outline">{label(requests[thread.id].status)}</Badge>}<span className="font-mono text-xs text-muted-foreground">{thread.id}</span><span className="ml-auto text-xs text-muted-foreground">{thread.messages.length} messages</span></div><div className="max-h-80 space-y-2 overflow-y-auto pr-1">{thread.messages.map((message) => <div key={message.id} className={cn("rounded-lg p-3 text-sm", message.sender_role === "homeowner" ? "bg-muted/50" : message.sender_role === "admin" ? "border border-violet-200 bg-violet-50" : "bg-accent/5")}><div className="mb-1 flex items-center gap-2"><span className="text-xs font-medium capitalize text-accent">{message.sender_role}</span><span className="text-[10px] text-muted-foreground">{formatDateTime(message.created_at)}</span></div><p className="whitespace-pre-wrap">{message.content}</p></div>)}</div></CardContent></Card>)}</div>}</div>;
}
function label(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (character) => character.toUpperCase()); }
function formatDateTime(value: string) { return new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
